### PR TITLE
HTTPS protocol, Average Rating in label, Default run-at and Readme update

### PR DESCRIPTION
**Pull request by sabatale**

### CODE REVIEW

**Comment by LenAnderson** [comment]
Do you mean to calculate the average rating across all movies or the average of the yearly averages? At the moment you are calculating the latter.

I am adding a commit that adds the average (across all movies) as a dataset to the chart. What do you think?

**Comment by LenAnderson** [comment]
Ok, I don't see and easy way of committing to the actual pull request. Pushing my changes just created a new branch in my repo.

Have a look here to see my changes: https://github.com/LenAnderson/IMDB-Average-Ratings/blob/pull/1/IMDB-Average-Ratings.user.js

**Comment by sabatale** [comment]
Good catch. It looks good to me!

**Comment by sabatale** [comment]
PS. The repo can probably be archived as IMDb does not show ratings on the actors pages anymore.

Ratings can probably be extracted through Cheerio but the loading times would increase significantly.

**Pull request closed without merging**
